development:
  adapter: mysql
  encoding: utf8
  database: bort_development
  username: root
  password:
  pool: 5
  socket: /var/mysql/mysql.sock
  
test:
  adapter: mysql
  encoding: utf8
  database: bort_test
  username: root
  password:
  pool: 5
  socket: /var/mysql/mysql.sock
  
staging:
  adapter: mysql
  encoding: utf8
  database: bort_staging
  username: root
  password:
  pool: 5
  
production:
  adapter: mysql
  encoding: utf8
  database: bort_production
  username: root
  password:
  pool: 5